[package]
name = "rocks-delay"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "^0.20"
anyhow = "^1.0"
chrono = "^0.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "^1.0", features = ["v4"] }
